### ISSUE TITLE
Please improve backend service robustness

### ISSUE THREAD

**Issue by Stean** [gidsi/eva-backend#6]
Hi,

from time to time, the backend crashes (seemlingly due to connection issues with the mongoDB instance) without automatically restarting.
It would be great, if such errors would not lead to a complete dying of the backend (e.g. by catching such errors or if existing docker mechanisms (like the docker health checks) would be leveraged to automatically trigger a restart).

```
2022/09/20 20:09:29 cron: panic running job: read tcp 172.16.238.3:51104->172.16.238.2:27017: i/o timeout
goroutine 226687 [running]:
github.com/robfig/cron.(*Cron).runWithRecovery.func1(0xc00017a2d0)
	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:161 +0x9e
panic(0x7a2800, 0xc07f764050)
	/usr/local/go/src/runtime/panic.go:969 +0x175
main.writeCalendar(0xc02acad1c8, 0x8, 0x0, 0x0, 0x0)
	/go/src/app/database.go:46 +0x35c
main.getCalendars()
	/go/src/app/calendar.go:26 +0x1ca
main.main.func1()
	/go/src/app/eva-backend.go:35 +0x2a
github.com/robfig/cron.FuncJob.Run(0x80de40)
	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:92 +0x25
github.com/robfig/cron.(*Cron).runWithRecovery(0xc00017a2d0, 0x865f40, 0x80de40)
	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:165 +0x59
created by github.com/robfig/cron.(*Cron).run
	/go/pkg/mod/github.com/robfig/cron@v1.2.0/cron.go:199 +0x76a
```

**Comment by gidsi** [comment]
Hey, this was handled before by systemd. Apparently it didn't make it to the new server (also I've lost access so I can't take care of it). Docker health checks are afaik not suitable for this use case.
